export { ReactComponent as IconNext } from './nextArrow.svg';
export { ReactComponent as IconHome } from './HomeGrey.svg';
export { ReactComponent as IconClass } from './ClassGrey.svg';
export { ReactComponent as IconSchedule } from './ScheduleGrey.svg';
export { ReactComponent as IconCommunity } from './CommunityGrey.svg';
export { ReactComponent as IconHomeSelect } from './HomeGreen.svg';
export { ReactComponent as IconClassSelect } from './ClassGreen.svg';
export { ReactComponent as IconScheduleSelect } from './ScheduleGreen.svg';
export { ReactComponent as IconCommunitySelect } from './CommunityGreen.svg';
